### ISSUE TITLE
Duplicate unique ID and Poor author/descripton in the .cia file

### ISSUE THREAD

**Issue by ksanislo** [Haze3ds/Twos--Woods#1]
@Haze3ds , 

It looks like you're using a duplicate of the TitleID/unique ID that is already in use by  Snake2DS: 
https://github.com/Jacudibu/Snake2DS/releases

Also, it looks like you've defined both the short name and long name SMDH fields as "LovePotion" .. Would you please update your build environment to use these to provide a new ID and proper naming info about your app?

Typical suggested usage by homebrew would be a short name like "Twos! Woods" and a long name of something like "Twos! Woods - 2048 mixed with Wario's Woods"

Can you please correct this information and build a new .cia, then create a new github release with the fixed version. That will allow [TitleDB](https://titledb.com/) to properly list your game. Feel free to resubmit the URL after you've corrected this.

**Comment by Haze3ds** [comment]
Thanks for taking a look at my Project. Ill rebuild the CIA. Id like to be in TiteDB. How do I go about making the changes you suggest, in the Makefile? Also what should I use as a  APP_UNIQUE_ID?

Here is my Makefile, I didnt keep the old one from the posted release so the unique id is lovepotion still.
https://drive.google.com/open?id=0BymzvO8X9PRGaEJnQmNJUWRTdVE

**Comment by ksanislo** [comment]
I'd change these three from that Makefile

APP_DESCRIPTION :=  Twos! Woods - 2048 mixed with Wario's Woods

APP_PRODUCT_CODE := CTR-P-TWWD
APP_UNIQUE_ID := 0xB05AD

The product code isn't particularly strict, you can actually make it any text of the same length, CTR-P-xxxx is the proper format though. You generally want it to be unique, as it makes your app easier to find in FBI's list to manage.

For picking a unique ID, it's a hex number that translates into the TitleID of the cia with the format of 00040000xxxxxx00

You'll need to check both titledb.com (homebrew) and 3dsdb.com (official titles) to make sure that you're picking something that won't conflict with any existing app or game.

**Comment by Haze3ds** [comment]
Thanks for the help, got the release up with your suggested info. Starting to work on this game again, hopefully much more playable to come. Will TitleDB download the latest release? I'm adding it to the database now.

**Comment by ksanislo** [comment]
Yeah, TDB will use github's API to find the latest non-prerelease that you have listed, and it'll regenerate all the info and and icon changes within about 15 minutes.
